# Generated by Django 3.2.8 on 2021-11-03 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_connections', '0002_auto_20211102_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='connectrequest',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ConnectionsList',
        ),
        migrations.DeleteModel(
            name='ConnectRequest',
        ),
    ]
