# Generated by Django 3.2.8 on 2021-11-13 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_users', '0032_alter_familymember_relation'),
        ('availability', '0002_rename_family_id_availability_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='website_users.familyprofile'),
        ),
    ]
