# Generated by Django 3.2.8 on 2021-11-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_alter_availability_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='days',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Weekdays', 'Weekdays'), ('Weekends', 'Weekends')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='time_of_day',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Noon', 'Noon'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening'), ('Night', 'Night'), ('Anytime', 'Anytime'), ('Unknown', 'Unknown')], max_length=255, null=True),
        ),
    ]
