# Generated by Django 3.2.8 on 2021-11-13 13:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0004_auto_20211112_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='time_of_day',
        ),
        migrations.AlterField(
            model_name='availability',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Weekdays', 'Weekdays'), ('Weekends', 'Weekends')], max_length=74, null=True),
        ),
    ]
