# Generated by Django 3.2.8 on 2021-11-02 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_model', '0003_rename_relation_status_customusermodel_family_relation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
