# Generated by Django 3.2.8 on 2021-11-07 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(choices=[('Afrikaans', 'Afrikaans'), ('Albanian', 'Albanian'), ('Amharic', 'Amharic'), ('Arabic', 'Arabic'), ('Armenian', 'Armenian'), ('Azerbaijani', 'Azerbaijani'), ('Basque', 'Basque'), ('Belarusian', 'Belarusian'), ('Bengali', 'Bengali'), ('Bosnian', 'Bosnian'), ('Bulgarian', 'Bulgarian'), ('Catalan', 'Catalan'), ('Cebuano', 'Cebuano'), ('Chewa', 'Chewa'), ('Chinese (Simplified)', 'Chinese (Simplified)'), ('Chinese (Traditional)', 'Chinese (Traditional)'), ('Corsican', 'Corsican'), ('Croatian', 'Croatian'), ('Czech', 'Czech'), ('Danish', 'Danish'), ('Dutch', 'Dutch'), ('English', 'English'), ('Esperanto', 'Esperanto'), ('Estonian', 'Estonian'), ('Filipino (Tagalog)', 'Filipino (Tagalog)'), ('Finnish', 'Finnish'), ('French', 'French'), ('Frisian', 'Frisian'), ('Galician', 'Galician'), ('Georgian', 'Georgian'), ('German', 'German'), ('Greek', 'Greek'), ('Gujarati', 'Gujarati'), ('Haitian Creole', 'Haitian Creole'), ('Hausa', 'Hausa'), ('Hawaiian', 'Hawaiian'), ('Hebrew', 'Hebrew'), ('Hindi', 'Hindi'), ('Hmong', 'Hmong'), ('Hungarian', 'Hungarian'), ('Icelandic', 'Icelandic'), ('Igbo', 'Igbo'), ('Indonesian', 'Indonesian'), ('Irish', 'Irish'), ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('Javanese', 'Javanese'), ('Kannada', 'Kannada'), ('Kazakh', 'Kazakh'), ('Khmer', 'Khmer'), ('Kinyarwanda', 'Kinyarwanda'), ('Korean', 'Korean'), ('Kurdish (Kurmanji)', 'Kurdish (Kurmanji)'), ('Kyrgyz', 'Kyrgyz'), ('Lao', 'Lao'), ('Latin', 'Latin'), ('Latvian', 'Latvian'), ('Lithuanian', 'Lithuanian'), ('Luxembourgish', 'Luxembourgish'), ('Macedonian', 'Macedonian'), ('Malagasy', 'Malagasy'), ('Malay', 'Malay'), ('Malayalam', 'Malayalam'), ('Maltese', 'Maltese'), ('Maori', 'Maori'), ('Marathi', 'Marathi'), ('Mongolian', 'Mongolian'), ('Myanmar (Burmese)', 'Myanmar (Burmese)'), ('Nepali', 'Nepali'), ('Norwegian (Bokmål)', 'Norwegian (Bokmål)'), ('Odia', 'Odia'), ('Pashto', 'Pashto'), ('Persian', 'Persian'), ('Polish', 'Polish'), ('Portuguese', 'Portuguese'), ('Punjabi (Gurmukhi)', 'Punjabi (Gurmukhi)'), ('Romanian', 'Romanian'), ('Russian', 'Russian'), ('Samoan', 'Samoan'), ('Scottish Gaelic', 'Scottish Gaelic'), ('Serbian', 'Serbian'), ('Shona', 'Shona'), ('Sindhi', 'Sindhi'), ('Sinhala', 'Sinhala'), ('Slovak', 'Slovak'), ('Slovenian', 'Slovenian'), ('Somali', 'Somali'), ('Sotho', 'Sotho'), ('Spanish', 'Spanish'), ('Sundanese', 'Sundanese'), ('Swahili', 'Swahili'), ('Swedish', 'Swedish'), ('Tajik', 'Tajik'), ('Tamil', 'Tamil'), ('Tatar', 'Tatar'), ('Telugu', 'Telugu'), ('Thai', 'Thai'), ('Turkish', 'Turkish'), ('Turkmen', 'Turkmen'), ('Ukrainian', 'Ukrainian'), ('Urdu', 'Urdu'), ('Uyghur', 'Uyghur'), ('Uzbek', 'Uzbek'), ('Vietnamese', 'Vietnamese'), ('Welsh', 'Welsh'), ('Xhosa', 'Xhosa'), ('Yiddish', 'Yiddish'), ('Yoruba', 'Yoruba'), ('Zulu', 'Zulu')], max_length=255, null=True)),
                ('family_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website_users.familyprofile')),
            ],
        ),
    ]
