# Generated by Django 3.2.8 on 2021-11-07 06:33

import custom_user_model.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.TextField(max_length=30)),
                ('profile_image', models.ImageField(blank=True, max_length=255, null=True, upload_to=custom_user_model.models.get_profile_image_filepath)),
                ('family_bio', models.TextField(blank=True, null=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('has_setup', models.BooleanField(default=False)),
                ('connections', models.ManyToManyField(related_name='connections', to=settings.AUTH_USER_MODEL)),
                ('hidden', models.ManyToManyField(related_name='toggled_profiles', to=settings.AUTH_USER_MODEL)),
                ('pending_requests', models.ManyToManyField(related_name='requests_pending', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
