# Generated by Django 3.2.8 on 2021-10-27 09:21

import custom_user_model.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyprofile',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=custom_user_model.models.get_profile_image_filepath),
        ),
    ]
