# Generated by Django 3.2.8 on 2021-10-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyprofile',
            name='family_name',
            field=models.TextField(max_length=30),
        ),
    ]
