# Generated by Django 3.2.8 on 2021-11-07 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('about', models.CharField(max_length=255, null=True)),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_users.familyprofile')),
            ],
        ),
    ]
