# Generated by Django 3.2.8 on 2021-10-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_users', '0005_alter_familyprofile_family_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyprofile',
            name='has_setup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='familyprofile',
            name='family_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
