# Generated by Django 3.2.8 on 2021-10-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_users', '0006_auto_20211028_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyprofile',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
