# Generated by Django 3.2.8 on 2021-11-07 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_users', '0007_alter_familymember_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymember',
            old_name='user',
            new_name='family',
        ),
    ]
