# Generated by Django 3.2.8 on 2021-11-03 02:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website_users', '0008_auto_20211029_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyprofile',
            name='connections',
            field=models.ManyToManyField(related_name='connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='pending_requests',
            field=models.ManyToManyField(related_name='requests_pending', to=settings.AUTH_USER_MODEL),
        ),
    ]
