# Generated by Django 3.2.8 on 2021-11-05 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website_users', '0009_auto_20211102_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyprofile',
            name='family_members',
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='family_members',
            field=models.ManyToManyField(related_name='family_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='familyprofile',
            name='hobbies',
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='hobbies',
            field=models.ManyToManyField(related_name='hobbies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='familyprofile',
            name='interests',
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='interests',
            field=models.ManyToManyField(related_name='interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='familyprofile',
            name='languages',
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='languages',
            field=models.ManyToManyField(related_name='languages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='familyprofile',
            name='locations',
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='locations',
            field=models.ManyToManyField(related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='familyprofile',
            name='schedule',
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='schedule',
            field=models.ManyToManyField(related_name='schedule', to=settings.AUTH_USER_MODEL),
        ),
    ]
