# Generated by Django 3.2.8 on 2021-11-07 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_users', '0010_familymember_user'),
        ('website_users', '0012_auto_20211107_1323'),
    ]

    operations = [
    ]
