# Generated by Django 3.2.8 on 2021-11-07 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_users', '0015_auto_20211107_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='user',
        ),
    ]
