# Generated by Django 3.2.8 on 2021-11-07 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website_users', '0016_remove_familymember_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='age_range',
        ),
        migrations.AddField(
            model_name='familymember',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website_users.familyprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familymember',
            name='about',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='familyprofile',
            name='connections',
            field=models.ManyToManyField(related_name='connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='familyprofile',
            name='hidden',
            field=models.ManyToManyField(related_name='toggled_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='familyprofile',
            name='pending_requests',
            field=models.ManyToManyField(related_name='requests_pending', to=settings.AUTH_USER_MODEL),
        ),
    ]
