# Generated by Django 3.2.8 on 2021-11-07 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_users', '0017_auto_20211107_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='user',
        ),
    ]
