# Generated by Django 3.2.8 on 2021-11-07 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_users', '0020_alter_familymember_age_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_member', to='website_users.familyprofile'),
        ),
    ]
