# Generated by Django 3.2.8 on 2021-11-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_users', '0022_familymember_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
