# Generated by Django 3.2.8 on 2021-11-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_users', '0026_addfamilymemberview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddFamilyMemberView',
        ),
    ]
