# Generated by Django 3.2.8 on 2021-11-08 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('age_range', '0004_agerange'),
        ('website_users', '0026_addfamilymemberview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddFamilyMemberView',
        ),
    ]
