# Generated by Django 3.2.8 on 2021-11-13 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_users', '0032_alter_familymember_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyprofile',
            name='locations',
        ),
    ]
