# Generated by Django 3.2.8 on 2021-11-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_users', '0033_remove_familyprofile_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyprofile',
            name='contact_info',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='familyprofile',
            name='family_bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
