# Generated by Django 3.2.8 on 2021-11-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_users', '0034_auto_20211117_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyprofile',
            name='family_bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
