# Generated by Django 3.2.8 on 2021-11-07 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobby',
            old_name='family_id',
            new_name='user',
        ),
    ]
