# Generated by Django 3.2.8 on 2021-10-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyPlusUser',
        ),
    ]
