# Generated by Django 3.2.8 on 2021-10-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_familyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyprofile',
            name='contact_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='family_members',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='languages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='locations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile'),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='schedule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familyprofile',
            name='family_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
