# Generated by Django 3.2.8 on 2021-10-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20211023_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pic_uploads'),
        ),
    ]
