# Generated by Django 3.2.8 on 2021-10-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_familyprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile'),
        ),
    ]
