# Generated by Django 3.2.8 on 2021-10-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_familyprofile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyprofile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='family_name',
            field=models.TextField(default='Set Up'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
