# Generated by Django 3.2.8 on 2021-10-25 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20211024_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyProfile',
        ),
    ]
