# Generated by Django 3.2.8 on 2021-11-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_auto_20211104_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagespecifier',
            name='language_mod',
            field=models.TextField(default='Language DB', max_length=50),
        ),
    ]
