# Generated by Django 3.2.8 on 2021-11-07 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_users', '0018_remove_familymember_user'),
        ('age_range', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agerange',
            name='family_member_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='website_users.familymember'),
            preserve_default=False,
        ),
    ]
