# Generated by Django 3.2.8 on 2021-11-07 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website_users', '0019_auto_20211107_1417'),
        ('age_range', '0003_delete_agerange'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(choices=[('On the way', 'On the way'), ('Baby (0-12 months)', 'Baby (0-12 months)'), ('Toddler (1-3 years)', 'Toddler (1-3 years)'), ('Preschooler (3-5 years)', 'Preschooler (3-5 years)'), ('Gradeschooler (5-12 years)', 'Gradeschooler (5-12 years)'), ('Teenager (12-17 years)', 'Teenager (12-17 years)'), ('Adult (18-24)', 'Adult (18-24)'), ('Adult (25-29)', 'Adult (25-29)'), ('Adult (30-34)', 'Adult (30-34)'), ('Adult (35-39)', 'Adult (35-39)'), ('Adult (40-44)', 'Adult (40-45)'), ('Adult (45-49)', 'Adult (45-49)'), ('Adult (50-54)', 'Adult (50-54)'), ('Adult (55-59)', 'Adult (55-59)'), ('Adult (60-64)', 'Adult (60-64)'), ('Older Adult (65-69)', 'Older Adult (65-69)'), ('Older Adult (70-74)', 'Older Adult (70-74)'), ('Older Adult (75-79)', 'Older Adult (75-79)'), ('Older Adult (80-84)', 'Older Adult (80-84)'), ('Older Adult (85-89)', 'Older Adult (85-89)'), ('Older Adult (90-94)', 'Older Adult (90-94)'), ('Older Adult (95-99)', 'Older Adult (95-99)'), ('Older Adult (100+)', 'Older Adult (100+)'), ('Older Adult (90-94)', 'Older Adult (90-94)'), ('Choose not to share', 'Choose not to share')], max_length=255, null=True)),
                ('family_member_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website_users.familymember')),
            ],
        ),
    ]
